import Navigation from "@/components/Navigation";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://bootswatch.com/5/cosmo/bootstrap.min.css"
        />
      </head>
      <body className={inter.className}>
        <Navigation />
        <main className="container py-4">{children}</main>
        <footer className="bg-dark text-light text-center">
          <div className="container p-4">
            <h1>&copy; Matias Choque Portafolio</h1>
            <p>2023 - {new Date().getFullYear()}</p>
            <p>All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
